In [5]:
from preprocessor import *

In [28]:
data = pd.read_csv('~/Documents/datasets/house_prices/train.csv')

In [29]:
print(data.shape)
data.head()

(1460, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [21]:
df = pd.DataFrame(data.isnull().sum(),columns=['nulls'])

In [18]:
df = df.sort_values(by='nulls',ascending=False)
df.iloc[:20,:]

              nulls
PoolQC         1453
MiscFeature    1406
Alley          1369
Fence          1179
FireplaceQu     690
LotFrontage     259
GarageYrBlt      81
GarageCond       81
GarageType       81
GarageFinish     81
GarageQual       81
BsmtFinType2     38
BsmtExposure     38
BsmtQual         37
BsmtCond         37
BsmtFinType1     37
MasVnrArea        8
MasVnrType        8
Electrical        1
Id                0

In [35]:
data.PoolQC = data["PoolQC"].fillna("None")
data.Alley = data["Alley"].fillna("None")
data.MiscFeature = data["MiscFeature"].fillna("None")
data.Fence = data["Fence"].fillna("None")
data.MasVnrArea = data["MasVnrArea"].fillna("None")
data.LotFrontage = data["LotFrontage"].fillna("None")
data.MasVnrType = data["MasVnrType"].fillna("None")
data.GarageType = data["GarageType"].fillna("None")
data.GarageCond = data["GarageCond"].fillna("None")
data.GarageQual = data["GarageQual"].fillna("None")
data.GarageFinish = data["GarageFinish"].fillna("None")
data.GarageYrBlt = data["GarageYrBlt"].fillna("None")
data.FireplaceQu = data["FireplaceQu"].fillna("None")
data.BsmtFinType1 = data["BsmtFinType1"].fillna("None")
data.BsmtCond = data["BsmtCond"].fillna("None")
data.BsmtQual = data["BsmtQual"].fillna("None")
data.BsmtFinType2 = data["BsmtFinType2"].fillna("None")
data.BsmtExposure = data["BsmtExposure"].fillna("None")
data.Electrical = data["Electrical"].fillna("None")

In [36]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65,8450,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,2,2008,WD,Normal,208500
1,2,20,RL,80,9600,Pave,None,Reg,Lvl,AllPub,...,0,None,None,None,0,5,2007,WD,Normal,181500
2,3,60,RL,68,11250,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,9,2008,WD,Normal,223500
3,4,70,RL,60,9550,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84,14260,Pave,None,IR1,Lvl,AllPub,...,0,None,None,None,0,12,2008,WD,Normal,250000

In [42]:
data.isnull().any()

Id               False
MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
                 ...
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 81, dtype: bool

In [120]:
X = data.drop(['Id','SalePrice'],axis=1)
dm_X = pd.get_dummies(X)
print("X shape: {}".format(X.shape))
print("X with dummies shape: {}".format(dm_X.shape))
y = data['SalePrice']

X shape: (1460, 79)
X with dummies shape: (1460, 837)

In [121]:
import pickle
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.externals import joblib
from sklearn.svm import SVR

sc = MinMaxScaler()
dm_X = sc.fit_transform(dm_X)
X_train, X_test, y_train ,y_test = train_test_split(dm_X, y,test_size=0.25, random_state= 42,shuffle=True)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

Accuracy on the training subset: 0.984
Accuracy on the testing subset: -152326783508704576.000

In [130]:
clf = RandomForestRegressor()
clf.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [131]:
print('Accuracy on the training subset: {:.3f}'.format(clf.score(X_train, y_train)))
print('Accuracy on the testing subset: {:.3f}'.format(clf.score(X_test, y_test)))

Accuracy on the training subset: 0.967
Accuracy on the testing subset: 0.886

In [132]:
filename = 'housing_model.pkl'
joblib.dump(clf,filename)

['housing_model.pkl']

In [2]:
from sklearn.externals import joblib
mdl = joblib.load('housing_model.pkl')

In [3]:
y_pred = mdl.predict(X_test)

NameError: name 'X_test' is not defined

In [40]:
val = pd.read_csv('~/Documents/datasets/house_prices/test.csv')

prep = Preprocessor()
val = val.drop(['Id'],axis=1)
cats, nums = prep.column_types(val)

val[cats] = val[cats].fillna("None",axis = 1)
val[nums] = val[nums].fillna(0,axis = 1)

In [41]:
print(val.columns)
print(val.shape)
val.head()

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition'],
      dtype='object')
(1459, 79)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,None,Reg,Lvl,AllPub,Inside,...,120,0,None,MnPrv,None,0,6,2010,WD,Normal
1,20,RL,81.0,14267,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,Gar2,12500,6,2010,WD,Normal
2,60,RL,74.0,13830,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,MnPrv,None,0,3,2010,WD,Normal
3,60,RL,78.0,9978,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,None,None,0,6,2010,WD,Normal
4,120,RL,43.0,5005,Pave,None,IR1,HLS,AllPub,Inside,...,144,0,None,None,None,0,1,2010,WD,Normal

In [46]:
X_val_cats = pd.get_dummies(val,columns = cats)
x_val_cats_df = pd.DataFrame(X_val_cats)

In [48]:
sc = MinMaxScaler

NameError: name 'MinMaxScaler' is not defined

In [47]:
X_val[nums].head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,730.0,140,0,0,0,120,0,0,6,2010
1,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,312.0,393,36,0,0,0,0,12500,6,2010
2,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,482.0,212,34,0,0,0,0,0,3,2010
3,60,78.0,9978,6,6,1998,1998,20.0,602.0,0.0,...,470.0,360,36,0,0,0,0,0,6,2010
4,120,43.0,5005,8,5,1992,1992,0.0,263.0,0.0,...,506.0,0,82,0,0,144,0,0,1,2010